FROM golang:alpine

LABEL author="MikZuit<https://github.com/mikzuit>"
LABEL author-site="https://mikzuit.com"

COPY dockerfiles/go-1.12/root /

RUN apk add --no-cache ca-certificates \
        dpkg \
        gcc \
        git \
        musl-dev \
        bash

ENV GOPATH /go
ENV PATH $GOPATH/bin:/usr/local/go/bin:$PATH
# set this line below in order to avoid '
ENV XDG_CACHE_HOME=/tmp/.cache

RUN mkdir -p "$GOPATH/src" "$GOPATH/bin" \
    && chmod -R 777 "$GOPATH" \
    && chmod +x /entrypoint.sh

RUN go get github.com/oxequa/realize
RUN go get github.com/gorilla/mux
RUN go get github.com/smartystreets/goconvey
RUN go get github.com/stretchr/testify/mock

WORKDIR $GOPATH
ENTRYPOINT ["/entrypoint.sh"]

CMD ["realize", "start"]
